name: TomLib
version: "1.2.11"
license: "GPL-2.0-or-later"
date: 2024-01-12
description: |
    The GAP Library of Tables of Marks

authors:
    - name: Thomas Merkwitz
      url: mailto:tmez2525@web.de
    - name: Liam Naughton
      url: mailto:l.naughton@wlv.ac.uk
    - name: Götz Pfeiffer
      url: mailto:goetz.pfeiffer@nuigalway.ie

maintainers:
    - name: Liam Naughton
      url: mailto:l.naughton@wlv.ac.uk
    - name: Götz Pfeiffer
      url: mailto:goetz.pfeiffer@nuigalway.ie

GAP: ">= 4.4"

needed-pkgs:
    - name: "atlasrep"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep"

suggested-pkgs:
    - name: "ctbllib"
      version: ">= 1.1"
      url: "https://www.math.rwth-aachen.de/~Thomas.Breuer/ctbllib"

www: https://gap-packages.github.io/tomlib
readme: README.md
packageinfo: https://gap-packages.github.io/tomlib/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/tomlib/releases/download/v1.2.11/tomlib-1.2.11.tar.gz

abstract: |
    The package contains the <span class="pkgname">GAP</span> Library of Tables of Marks

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    table of marks, Burnside matrix, subgroup lattice, finite simple groups, Moebius function, Euler function.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>MNP24</span>]   <b class='BibAuthor'>Merkwitz, T., Naughton, L. and Pfeiffer, G.</b>,
     <i class='BibTitle'>TomLib, The GAP Library of Tables of Marks,
             Version 1.2.11</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/tomlib">https://gap-packages.github.io/tomlib</a></span>.
    </p>
    

bibtex: |
    @misc{ TomLib1.2.11,
      author =           {Merkwitz, T. and Naughton, L. and Pfeiffer, G.},
      title =            {{TomLib},   The   GAP  Library  of  Tables  of  Marks,
                          {V}ersion 1.2.11},
      month =            {Jan},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/tomlib}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{tomlib}}},
      keywords =         {table  of  marks;  Burnside  matrix; subgroup lattice;
                          finite simple groups; Moebius function; Euler function},
      printedkey =       {MNP24}
    }

